### ISSUE TITLE
Do you support Uncertainty Analysis module ?

### ISSUE THREAD

**Issue by scalet98** [respec/HSPsquared#23]
Hello ! 
I've just joined this website. And I found your organization. 
I am a Ph.D. candidate for Hydrologic & water quality modeler under the climate change scenario.
For my studies I want some uncertainty analysis in terms of various variables. 

However, from some conference material I found that your organization developed some modules to link HSPF input and output file to DAKOTA program... 

Do you support those program or module? 

Sincerely yours, 
Jiheon Lee.

**Comment by timcera** [comment]
I don't know about HSPF and DAKOTA, however there has been some work and utilities created to support PEST (http://pesthomepage.org/).  One of the PEST utilities was developed into TSPROC (https://pubs.usgs.gov/tm/tm7c7/) of which I am one of the authors and was responsible for improving support for WDM files.  TSPROC works very closely with PEST and can in one mode create a PEST control file and in another mode handle all HSPF model post-processing so that model results are easily readable by PEST.

**Comment by timcera** [comment]
Should add that PEST is a suite of programs, some of which can be used for uncertainty analysis.

**Comment by scalet98** [comment]
> Should add that PEST is a suite of programs, some of which can be used for uncertainty analysis.



> I don't know about HSPF and DAKOTA, however there has been some work and utilities created to support PEST (http://pesthomepage.org/). One of the PEST utilities was developed into TSPROC (https://pubs.usgs.gov/tm/tm7c7/) of which I am one of the authors and was responsible for improving support for WDM files. TSPROC works very closely with PEST and can in one mode create a PEST control file and in another mode handle all HSPF model post-processing so that model results are easily readable by PEST.

Dear timcera, 

I found your reply too late. But It is very informative. 
I am going to browse your sites. 
Thanks

Jiheon Lee :)
